parameters:
  c3_charts.twig_extension.class: Muspelheim\C3ChartsBundle\Twig\C3Extension

services:
  c3_charts.twig.highcharts_extension:
    class: "%c3_charts.twig_extension.class%"
    tags:
        - { name: twig.extension }
